### ISSUE TITLE
Nemaspace changed

### ISSUE THREAD

**Issue by ghost** [popphp/popphp.org#1]
Hello nick,

please paid attention when you changed the namespace or class location. 

In the versions current online you have moved the `Request` and `Response` classes of the **Http** package to `Http\Server\Request` and `Hettp\Server\Response` but in the applications you have not updated the request for the namesaps that are therefore not found.

For the application **popphp.org**, I have tried only this, cahnge all declarations

```php
use Pop\Http\Request;
use Pop\Http\Response;
```

in

```php
use Pop\Http\Server\Request;
use Pop\Http\Server\Response;
```
For the rest ... what can I say ... you're strong ... keep it up.

Adriano

**Comment by nicksagona** [comment]
Adriano - please pay attention to the chat room. Multiple announcements and requests for input on this *very exact issue and update* were made there. This was announced and done intentionally for better code organization and separation of concerns between the Client and Server classes. Backwards compatibility breaks regarding method signatures and class properties were kept to a absolute minimum and the *only* BC break was the intentional class reorganization from `Pop\Http\Request` and `Pop\Http\Response` to `Pop\Http\Server\Request` and `Pop\Http\Server\Response`, respectively.

All of the main components that utilize the `pop-http` component have been updated appropriately EXCEPT for support repos such as `popphp-skeleton`, `popphp-tutorial`, `popphp.org`, etc. As has been announced previously, Pop 4.5 is currently in beta, with only one component remaining to upgrade. Once that is complete, a full release will be issued and the remaining support repos will be updated accordingly.

This topic is the last five messages in the chat room and only one person responded with some input/support. I believe you are a member of the chat room. You are encouraged to follow there and give feedback/input.

Thank You,

Nick

**Comment by ghost** [comment]
Hi nick, sorry but I took a quick look at the sources to see what changes you had made.

Unfortunately, the work absorbs me to the point that I can't even follow the chats.

See you next time and keep it up.
